### PR TITLE
render policies for 1.11

### PR DESCRIPTION
**Pull request by JimBugwadia**
## Related issue #

N/A

## Proposed Changes

render policies

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Review by chipzoller — CHANGES_REQUESTED** [review]
Because `render` does not remove subdirectories from the parent (see https://github.com/kyverno/website/issues/929), it must be done manually. I see that wasn't the case here so there will be essentially duplicate policies which clean up bare Pods since "prevent-bare-pods" was a rename. [This one](https://github.com/kyverno/website/tree/main/content/en/policies/other/prevent-naked-pods) should get deleted. Ensuring the `-c` flag to `render` removes subdirectories would fix this.

**Comment by JimBugwadia** [comment]
> #929

done!

**Comment by chipzoller** [comment]
Nothing further appears to have been done here.

**Comment by JimBugwadia** [comment]
Updated deleted dirs - please check.

**Review by chipzoller — APPROVED** [review]
LGTM

**Pull request merged**
