### PR TITLE
Upgrade to docsy 0.7.0

### PR DESCRIPTION
**Pull request by deining**
This upgrades the site to docsy 0.7.0.
Please note that this is a hack only. The key problem here is that the Kyverno project defines its one `assets/scss/main.css`. This is not considered best practice and was causing trouble when during upgrade. I solved it by adding a missing import to `main.css` which resolved the issue. As mentioned above,  this is a hack only. I leave it up to the authors to move the custom content form `main.css` into `_styles_project.scss` and `_variables_project.scss` respectively and remove `main.css` afterwards.

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
Thank you very much for this, @deining! Appreciate you for trying to help us out. Unfortunately, I guess due to those custom changes, the [site preview](https://deploy-preview-893--kyverno.netlify.app/) looks to have some CSS issues. Obviously not asking you to help us fix those, but we may have to pause on this PR until we can get a contractor to help us out.

**Comment by chalin** [comment]
@chipzoller - if you open a [CNCF servicedesk](https://cncfservicedesk.atlassian.net/servicedesk/customer/portal/1) ticket, we can see if the techdocs team might be able to allocate resources to help out. /cc @nate-double-u

**Comment by chipzoller** [comment]
Thanks for the offer but I haven't had a good experience with using the CNCF help desk for website assistance. I think we'll have to seek outside expertise.

**Comment by chalin** [comment]
@chipzoller - wishing you better servicedesk experiences in the future, and a smooth migration for your project -- FYI, the following blog post might help: [Migrating to Bootstrap 5.2](https://www.docsy.dev/blog/2023/bootstrap-5-migration/).

**Comment by chipzoller** [comment]
Thanks very much once again here, @deining. We got this addressed in #904 thanks to @onweru.

**Pull request closed without merging**
