### PR TITLE
fix: search

### PR DESCRIPTION
**Pull request by eddycharly**
Fix search.

### CODE REVIEW

**Comment by chipzoller** [comment]
Would prefer to use #1030

**Comment by eddycharly** [comment]
> Would prefer to use https://github.com/kyverno/website/pull/1030

Didn't see this PR. When is this going to land ?

**Comment by chipzoller** [comment]
When he gets some time to fix a few remaining items.

**Comment by eddycharly** [comment]
Ok, added to the agenda for tomorrow meeting.

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
