### PR TITLE
WIP: feat: initial commit for new blog post (Check image signatures and add digests with KMS Support)

### PR DESCRIPTION
**Pull request by developer-guy**
Signed-off-by: Batuhan Apaydın <batuhan.apaydin@trendyol.com>

### CODE REVIEW

**Comment by chipzoller** [comment]
I think this would probably be more appropriate contained within the existing verify-images page. We aren't currently set up to do full on blog posts but it's something we've thought about.

@JimBugwadia do you have a preference?

**Comment by chipzoller** [comment]
Converted to draft.

**Comment by JimBugwadia** [comment]
Chip, I agree.  For now, we can add a new section in the existing [verify-images](https://kyverno.io/docs/writing-policies/verify-images/) page, but the style will need to be more user documentation than a blog post.

Should we consider adding a Kyverno blog on kyverno.io? Or is it better to host on medium, etc.

Another option is to do a CNCF or Kubernetes blog post.

@developer-guy - what do you think?

**Comment by developer-guy** [comment]
friendly ping @JimBugwadia, I was working on to make it happen the whole demo but got the following error:

```shell
$ kubectl run signed --image=devopps/golang:1.17-alpine
Error from server: admission webhook "mutate.kyverno.svc-fail" denied the request:

resource Pod/default/signed was blocked due to the following policies

check-image:
  check-image: 'image signature verification failed for docker.io/devopps/golang:1.17-alpine:
    loading credentials: open 'gcpkms:/projects/batuhan-workspace/locations/global/keyRings/test/cryptoKeys/cosign':
    no such file or directory'
```

Here is my policy:

```YAML
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        resources:
          kinds:
            - Pod
      verifyImages:
      - image: "*"
        key: gcpkms://projects/batuhan-workspace/locations/global/keyRings/test/cryptoKeys/cosign
```

I noticed that this part `gcpkms://` is wrong. One slash character is missing, it is not the same as I defined in the ClusterPolicy.

>  loading credentials: open 'gcpkms:/projects/batuhan-workspace/locations/global/keyRings/test/cryptoKeys/cosign'

 What did I do wrong? Can you please help me? @JimBugwadia

**Comment by JimBugwadia** [comment]
Can you try wrapping the value in quotes?

```
      verifyImages:
      - image: "*"
        key: "gcpkms://projects/batuhan-workspace/locations/global/keyRings/test/cryptoKeys/cosign"
```

**Comment by developer-guy** [comment]
> Can you try wrapping the value in quotes?
> 
> ```
>       verifyImages:
>       - image: "*"
>         key: "gcpkms://projects/batuhan-workspace/locations/global/keyRings/test/cryptoKeys/cosign"
> ```

nothing changed :/

**Comment by JimBugwadia** [comment]
@developer-guy - I wrote a small test to figure out why this error ocurrs:

```golang
func Test_Provider(t *testing.T) {
	test := "gcpkms://projects/batuhan-workspace/locations/global/keyRings/test/cryptoKeys/cosign"
	v, e := sigs.PublicKeyFromKeyRef(context.TODO(), test)
	assert.NilError(t, e)
	assert.Assert(t, v != nil)
}
```

The problem is that the KMS requires a GCP client which is not initialized in the Kyverno container:

In `pkg/signature/kms/kms.go`:

```golang
func init() {
	ProvidersMux().AddProvider(aws.ReferenceScheme, func(ctx context.Context, keyResourceID string, hashFunc crypto.Hash) (SignerVerifier, error) {
		return aws.LoadSignerVerifier(keyResourceID)
	})
	ProvidersMux().AddProvider(azure.ReferenceScheme, func(ctx context.Context, keyResourceID string, hashFunc crypto.Hash) (SignerVerifier, error) {
		return azure.LoadSignerVerifier(ctx, keyResourceID, hashFunc)
	})
	ProvidersMux().AddProvider(gcp.ReferenceScheme, func(ctx context.Context, keyResourceID string, _ crypto.Hash) (SignerVerifier, error) {
		return gcp.LoadSignerVerifier(ctx, keyResourceID)
	})
	ProvidersMux().AddProvider(hashivault.ReferenceScheme, func(ctx context.Context, keyResourceID string, hashFunc crypto.Hash) (SignerVerifier, error) {
		return hashivault.LoadSignerVerifier(keyResourceID, hashFunc)
	})
}


```

```golang

// LoadSignerVerifier generates signatures using the specified key object in GCP KMS and hash algorithm.
//
// It also can verify signatures locally using the public key. hashFunc must not be crypto.Hash(0).
func LoadSignerVerifier(defaultCtx context.Context, referenceStr string) (*SignerVerifier, error) {
	g := &SignerVerifier{
		defaultCtx: defaultCtx,
	}

	var err error
	g.client, err = newGCPClient(defaultCtx, referenceStr)
	if err != nil {
		return nil, err
	}

	return g, nil
}

```

The `newGCPClient` returns an error, which then falls through to the file provider which calls a "filepath.Clean" which strips the double slash.

So, the issue is not really the double slash, but that there is no GCP client installed.

Any ideas on how we can make this work in a container?

**Comment by developer-guy** [comment]
> @developer-guy - I wrote a small test to figure out why this error ocurrs:
> 
> ```go
> func Test_Provider(t *testing.T) {
> 	test := "gcpkms://projects/batuhan-workspace/locations/global/keyRings/test/cryptoKeys/cosign"
> 	v, e := sigs.PublicKeyFromKeyRef(context.TODO(), test)
> 	assert.NilError(t, e)
> 	assert.Assert(t, v != nil)
> }
> ```
> 
> The problem is that the KMS requires a GCP client which is not initialized in the Kyverno container:
> 
> In `pkg/signature/kms/kms.go`:
> 
> ```go
> func init() {
> 	ProvidersMux().AddProvider(aws.ReferenceScheme, func(ctx context.Context, keyResourceID string, hashFunc crypto.Hash) (SignerVerifier, error) {
> 		return aws.LoadSignerVerifier(keyResourceID)
> 	})
> 	ProvidersMux().AddProvider(azure.ReferenceScheme, func(ctx context.Context, keyResourceID string, hashFunc crypto.Hash) (SignerVerifier, error) {
> 		return azure.LoadSignerVerifier(ctx, keyResourceID, hashFunc)
> 	})
> 	ProvidersMux().AddProvider(gcp.ReferenceScheme, func(ctx context.Context, keyResourceID string, _ crypto.Hash) (SignerVerifier, error) {
> 		return gcp.LoadSignerVerifier(ctx, keyResourceID)
> 	})
> 	ProvidersMux().AddProvider(hashivault.ReferenceScheme, func(ctx context.Context, keyResourceID string, hashFunc crypto.Hash) (SignerVerifier, error) {
> 		return hashivault.LoadSignerVerifier(keyResourceID, hashFunc)
> 	})
> }
> ```
> 
> ```go
> // LoadSignerVerifier generates signatures using the specified key object in GCP KMS and hash algorithm.
> //
> // It also can verify signatures locally using the public key. hashFunc must not be crypto.Hash(0).
> func LoadSignerVerifier(defaultCtx context.Context, referenceStr string) (*SignerVerifier, error) {
> 	g := &SignerVerifier{
> 		defaultCtx: defaultCtx,
> 	}
> 
> 	var err error
> 	g.client, err = newGCPClient(defaultCtx, referenceStr)
> 	if err != nil {
> 		return nil, err
> 	}
> 
> 	return g, nil
> }
> ```
> 
> The `newGCPClient` returns an error, which then falls through to the file provider which calls a "filepath.Clean" which strips the double slash.
> 
> So, the issue is not really the double slash, but that there is no GCP client installed.
> 
> Any ideas on how we can make this work in a container?

OMG! yes, the error is coming from [here](https://github.com/sigstore/cosign/blob/0c771f85cd2d16e0854b8688da10fc7e203a5a8d/pkg/blob/load.go#L40). But, I thought that the workload identity feature should work for initiating the GCP client, I gave the right permissions to the ServiceAccount of the kyverno within the kyverno namespace. @dlorenc can you help us a bit? 🙏

**Comment by developer-guy** [comment]
We actually did the same effort a long time ago for the FalcoSidekick project. In this code, we've used the GCP SecretManager client in order to read secret that includes kubeconfig file, and again we've used the workload identity feature for this. Am I right? @dentrax
https://falco.org/blog/falcosidekick-response-engine-part-7-cloud-functions/

**Comment by developer-guy** [comment]
@JimBugwadia it is actually working when I try it with another Pod created by the following commands:

```shell
 kubectl run -it --rm \
  --image google/cloud-sdk:slim \
  --serviceaccount kyverno-service-account \
  --namespace kyverno \
  workload-identity-test
```

Screen Shot 2021-11-11 at 15 53 53

**Comment by chipzoller** [comment]
Is this still being worked on?

**Comment by chipzoller** [comment]
Bump

**Comment by developer-guy** [comment]
hello @chipzoller, can you please re-open this issue because we've fixed the problem which is a blocker thing to write this, please [see](https://github.com/sigstore/sigstore/issues/138#issuecomment-1056571041). So, I'm ready to write the blog post right now.

**Comment by chipzoller** [comment]
The problem here is that the website currently isn't set up properly to have a blog, and putting this where the initial PR had it isn't really the appropriate place. I had started to work on adding a real blog section in my fork (since deleted) but haven't gotten back to it. If you'd like to pick up the gauntlet and figure out how to add a blog section to the website and contribute a first post, that'd be wonderful, but we do need the blog section before the blog post.

**Comment by developer-guy** [comment]
aah okay, maybe we can publish this blog post on sigstore medium, WDYT?
cc: @dlorenc

**Comment by dlorenc** [comment]
> aah okay, maybe we can publish this blog post on sigstore medium, WDYT?

sure!

**Pull request closed without merging**
