### PR TITLE
fix(docs): Updated mutateExistingOnPolicyUpdate documentation to include validation info

### PR DESCRIPTION
**Pull request by mvaal**
## Proposed Changes

Documentation around `mutateExistingOnPolicyUpdate` was not complete and I kept running into the same issue forgetting to include the mutate target. This add that additional information to the documentation.

Here is the corresponding kyverno validation code: https://github.com/kyverno/kyverno/blob/43173e6c76a6381ab27b8b2979c82d265c605ccf/api/kyverno/v1/spec_types.go#L360

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by mvaal** [comment]
Also, this documentation seems to be wrong:

```
When defining a list of targets[], the fields name and namespace are not strictly required but encouraged. If omitted, it implies a wildcard ("*") for the omitted field which can have unintended impact on other resources.
```
From my experience, namespace is required. I can make that fix here as well if confirmed.

**Comment by realshuting** [comment]
Thanks for the contribution @mvaal !

> Also, this documentation seems to be wrong:
> 
> ```
> When defining a list of targets[], the fields name and namespace are not strictly required but encouraged. If omitted, it implies a wildcard ("*") for the omitted field which can have unintended impact on other resources.
> ```
> 
> From my experience, namespace is required. I can make that fix here as well if confirmed.

Why namespace is required for targets? A target could be a cluster-wide resource.

**Comment by mvaal** [comment]
Hey @realshuting!
> Why namespace is required for targets? A target could be a cluster-wide resource.
That was my use case. I was running into some error where it kept saying that `targets[*].namespace` was required, but now I am unable to reproduce it, so you can ignore that comment. Sorry!

**Review by realshuting — APPROVED** [review]
Thanks for your contribution @mvaal !

**Comment by mvaal** [comment]
I fixed a consistency issue and updated the docs to be a little more readable based on conversation found here:
https://kubernetes.slack.com/archives/CLGR9BJU9/p1726606583673049

**Review by JimBugwadia — APPROVED** [review]

**Pull request merged**
