### PR TITLE
minor update installation methods

### PR DESCRIPTION
**Pull request by dixudx**
## Proposed Changes

Minor update the installation part for better guidance, especially for beginners.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [] I have signed off my issue.

### CODE REVIEW

**Comment by dixudx** [comment]
cc @realshuting @JimBugwadia

**Review by realshuting — APPROVED** [review]
/lgtm

**Comment by JimBugwadia** [comment]
The changes look good, but there seem to be some errors due to broken links.

Should we create a separate issue for that?

**Comment by JimBugwadia** [comment]
Created https://github.com/kyverno/website/issues/1340.

**Review by JimBugwadia — APPROVED** [review]

**Pull request merged**
