### PR TITLE
making the front matter consistent across the project

### LINKED ISSUE #1082: [Bug] making the front matter consistent across the project
### Page link

_No response_

### Description

Not a major update but the front matter is inconsistent across different files in the project. e.g. 

For the [community/_index page](https://github.com/kyverno/website/blob/main/content/en/Community/_index.md?plain=1) we have - 
```
---
title: Community
linkTitle: "Community"
type: docs
---
```

While for [docs/introduct/_index page](https://github.com/kyverno/website/blob/main/content/en/docs/Introduction/_index.md?plain=1) we have 
```
---
title: "Introduction"
linkTitle: "Introduction"
weight: 10
```

### Expected behavior

It's a minor update but we should follow the actual Docsy format for front matter i.e.
```
---
title: "My amazing new section"
weight: 1
type: docs
description: >
  A special section with a docs layout.  
---
```

### Slack discussion

_No response_

### PR DESCRIPTION
**Pull request by 1Shubham7**
## Related issue #

Fixes #1082

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by 1Shubham7** [comment]
sorry for too many commits, changes from initial commits have been removed later.

**Review by chipzoller — COMMENTED** [review]
Thank you for attempting to find something to contribute, but I really don't think this is something we need to worry about. Strings in YAML/TOML do not need to be quoted (`title` field) and use of a folded line scalar is only for convenience when lines run too long. Neither of these actually change the display/rendering of the text.

**Comment by 1Shubham7** [comment]
yes @chipzoller, it doesn't change anything. I thought we should have similar format in all the files.

**Comment by chipzoller** [comment]
The only thing of value here would be to standardize on no quotes for string values and no folded line scalar. This would standardize frontmatter and also simplify things a bit.

**Comment by chipzoller** [comment]
Also, I've noticed here and elsewhere that you are not signing off on your git commits. Please change your editor so you sign off on _every_ commit. This is a requirement of not just Kyverno but basically all CNCF projects and others.

**Comment by 1Shubham7** [comment]
> Also, I've noticed here and elsewhere that you are not signing off on your git commits. Please change your editor so you sign off on _every_ commit. This is a requirement of not just Kyverno but basically all CNCF projects and others.

my bad. will make sure to sign off my commits for here onwards.

**Pull request closed without merging**
