### PR TITLE
Policies page enhancements

### PR DESCRIPTION
**Pull request by onweru**
@chipzoller , @JimBugwadia, I made a few improvements based on some cards that Chip created.

#### Improvements

1. [Add note to the top of the policies page](https://github.com/kyverno/website/projects/3#column-15055985)
2. [extend code blocks' width](https://github.com/kyverno/website/projects/3#card-64762200)
3. [Improve filter on mobile](https://github.com/kyverno/website/projects/3#card-64582384)
4. [Add a back to `all policies` button](https://github.com/kyverno/website/projects/3#card-64762195)
5. [Remove url query from policy single pages](https://github.com/kyverno/website/projects/3#card-64762205)

### CODE REVIEW

**Comment by chipzoller** [comment]
@onweru Looks good, and thanks much! One thing I see is the code block functions don't seem to be active on mobile. Is that by design? Also, the wrap line function doesn't seem to be taking into consideration the expanded code block window. See with https://deploy-preview-255--kyverno.netlify.app/policies/other/unique-ingress-paths/

**Comment by onweru** [comment]
> @onweru Looks good, and thanks much! One thing I see is the code block functions don't seem to be active on mobile. Is that by design? Also, the wrap line function doesn't seem to be taking into consideration the expanded code block window. See with https://deploy-preview-255--kyverno.netlify.app/policies/other/unique-ingress-paths/

@chipzoller, I'll double check that.

**Comment by chipzoller** [comment]
@onweru awaiting checks...

**Comment by JimBugwadia** [comment]
Looks great, thanks @onweru!

**Review by JimBugwadia — APPROVED** [review]

**Pull request merged**
