### PR TITLE
fix: metrics docs

### LINKED ISSUE #760: [Enhancement] Document missing 1.9 metrics
### Description

Metrics in https://github.com/kyverno/kyverno/pull/5494 are not documented.

### Slack discussion

_No response_

### LINKED ISSUE #769: [Enhancement] Add documentation for Cleanup Controller `cleanup_controller_deletedobjects` metric
### Description

Related Issue: https://github.com/kyverno/kyverno/pull/6127

### Slack discussion

_No response_

### PR DESCRIPTION
**Pull request by eddycharly**
Closes #760
Closes #769 

This PR fix various metrics docs issues:
- incomplete metric names for histograms
- incomplete labels list for `kyverno_admission_review_duration_seconds`
- incomplete labels list for `kyverno_policy_execution_duration_seconds`
- incomplete labels list for `kyverno_admission_requests_total`
- missing docs for `kyverno_http_requests_duration_seconds`
- missing docs for `kyverno_controller_reconcile_total`
- missing docs for `kyverno_controller_requeue_total`
- missing docs for `kyverno_controller_drop_total`
- missing docs for `kyverno_cleanup_controller_errors_total`
- missing docs for `kyverno_cleanup_controller_deletedobjects_total`
- order labels table by label name
- improved pages layout

### CODE REVIEW

**Comment by chipzoller** [comment]
You putting cleanup here as well? This account for all missing metrics too?

**Comment by eddycharly** [comment]
I will do everything here

**Comment by eddycharly** [comment]
@chipzoller we should be good

**Review by chipzoller — APPROVED** [review]

**Comment by eddycharly** [comment]
I don't think we need to change anything on the index page, what should be changed ?

**Comment by chipzoller** [comment]
References to the Helm values snippets? Installation instructions? Have you checked all of it for 100% accuracy?

**Comment by eddycharly** [comment]
Ah, you're right, i missed that.

**Comment by eddycharly** [comment]
@chipzoller i update the index

**Review by chipzoller — APPROVED** [review]
Thanks very much!

**Pull request merged**
