### PR TITLE
Patch regression after #893

### PR DESCRIPTION
**Pull request by onweru**
## Related issue #

#893

## Proposed Changes

This PR

1. Applies [this recommendation](https://github.com/google/docsy/issues/1556#issuecomment-1583341785)
2. Fixes menu link alignment regression after #893 
3. Re-applies smooth scroll 
4. Fixes a markdown bug in the footer section

The changes here were applied on top of #893

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
@deining would you kindly confirm that this PR incorporates the changes you recommended in your PR #893 to make the site more compatible with Docsy recommendations and future upgrades? Thanks very much.

**Comment by deining** [comment]
> @deining would you kindly confirm that this PR incorporates the changes you recommended in your PR #893

This PR looks good to me!
I do have one recommendation though: hugo `v0.114.0` was released just yesterday, so you can use this version for your deployment.
Glad to see your site at docsy v0.7.0 now!

**Comment by chipzoller** [comment]
Thanks, yes I see in the logs it's using Go 1.14. But that's not defined anywhere in the site nor is it in Netlify. Where is that coming from? In order to use Node 18 I had to set an environment variable in Netlify since we couldn't figure that out either. Any ideas or advice, @deining?

**Comment by deining** [comment]
> Thanks, yes I see in the logs it's using Go 1.14. But that's not defined anywhere in the site nor is it in Netlify. Where is that coming from? In order to use Node 18 I had to set an environment variable in Netlify since we couldn't figure that out either. Any ideas or advice, @deining?

https://docs.netlify.com/configure-builds/manage-dependencies/#go

You can set `GO_VERSION` as environment variable, too. Or, what you also can do:
In `netlify.toml`add these lines:

```
GO_VERSION = 1.20.5
NODE_VERSION = 18.16.0
```

**Comment by chipzoller** [comment]
Thanks, good suggestion. @onweru could you incorporate those changes here?

**Comment by chipzoller** [comment]
@deining, I'm seeing that if I remove the env var from the Netlify side and add it here in `netlify.toml` that the deployment preview is once again failing. It's also not picking up the Go version even though it is specified. Any idea why that is?

**Comment by chipzoller** [comment]
Looks like the latest change did the trick!

**Comment by chipzoller** [comment]
Sorry for the delay here, @onweru. I noticed that a patch to 0.7 was released. Would you mind bumping up to that so we get the fixes, please?

**Comment by chipzoller** [comment]
Not that it's necessarily a bad thing, but did you notice that code blocks now are slightly different?

## New

image

## Old

image

**Comment by onweru** [comment]
@chipzoller, would you like me to restore the old format?

**Comment by chipzoller** [comment]
Not necessarily, but what was the source or reason for the different styling? Is it something that could break in the future with Docsy upgrades potentially?

**Comment by chipzoller** [comment]
I do see a problem with how Mermaid diagrams are being rendered in these changes, however, and this would need to be addressed.

## New

image

## Old

image

**Comment by onweru** [comment]
> Not necessarily, but what was the source or reason for the different styling? Is it something that could break in the future with Docsy upgrades potentially?

The Docsy upgrade introduced styling changes. Future Docsy upgrades could contain more styling changes. We would have to evaluate if we like those changes or not.

**Comment by onweru** [comment]
I will fix the regressions.

**Comment by chipzoller** [comment]
This is somewhat of a more minor concern, but I am seeing code blocks with quite a bit more padding around the actual text. See https://deploy-preview-904--kyverno.netlify.app/docs/installation/uninstallation/#uninstall-kyverno-with-yaml

New

image

Old

image

**Comment by chipzoller** [comment]
In https://deploy-preview-904--kyverno.netlify.app/docs/writing-policies/match-exclude/#match-statements have you noticed that the newer inline code styling doesn't seem to be applied to code inside tip boxes?

New

image


Old

image

**Comment by chipzoller** [comment]
This is looking good so far 👍

**Comment by chipzoller** [comment]
Just a couple things and I think we're good, @onweru.

**Review by chipzoller — APPROVED** [review]
Thanks so much!

**Pull request merged**
