### PR TITLE
[1.9] add Debug Mode flag to the doc

### PR DESCRIPTION
**Pull request by yimikao**
## Related issue #
[#3411](https://github.com/kyverno/kyverno/issues/1334)
[Pull Request](https://github.com/kyverno/kyverno/pull/5024)

## Proposed Changes
Adds the `--dumpPayload` flag that toggles debug mode to the list of container flags.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [ ] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
@yimikao please link to relevant issues/PRs on kyverno/kyverno. A title is not sufficient enough to know what to document.

**Comment by yimikao** [comment]
@chipzoller ✅

**Comment by chipzoller** [comment]
Thank you

**Comment by chipzoller** [comment]
Thank you, @yimikao! Because of conflicts and that I'm working on the 1.9 updates, I've incorporated these changes into my fork and will be submitting a new PR. Closing this.

**Pull request closed without merging**
