### PR TITLE
[1.13] Change: update on metrics exposure config

### PR DESCRIPTION
**Pull request by NeuroticalT**
## Related issue #

Issue - [kyverno/kyverno/9998](https://github.com/kyverno/kyverno/issues/9998)
PR - [kyverno/kyverno/10016](https://github.com/kyverno/kyverno/pull/10016)

@chipzoller, @realshuting 

## Proposed Changes

Added a couple explanatory examples of metric exposure configuration.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Review by realshuting — APPROVED** [review]

**Comment by chipzoller** [comment]
Looks fine. Code PR needs to be merged first.

**Comment by chipzoller** [comment]
@NeuroticalT, the base branch here was wrong so I updated to `main`. All changes first go to `main` and then may or may not be cherry picked. There are now conflicts to resolve if you please.

**Review by chipzoller — CHANGES_REQUESTED** [review]
Please address conflicts as the base branch was set incorrectly.

**Comment by realshuting** [comment]
Sent https://github.com/kyverno/website/pull/1363 to `main` (1.13). Will backport it to 1.12.x.

**Pull request closed without merging**
