### PR TITLE
fix: Updated doc for metric kyverno_policy_results_total to kyverno_policy_results #1325

### LINKED ISSUE #1325: [Bug] update Policy and Rule Execution metric's name
### Page link

https://kyverno.io/docs/monitoring/policy-results-info/

### Description

The metric `kyverno_policy_results_total` was renamed to `kyverno_policy_results` via this [PR](https://github.com/kyverno/kyverno/pull/6781), the name in the document needs to be updated.

### Expected behavior

See above.

### Slack discussion

_No response_

### PR DESCRIPTION
**Pull request by praddy26**
## Related issue #
Fixes #1325

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by realshuting** [comment]
Please add close keyword ("close") to auto-close the issue.

**Comment by praddy26** [comment]
> Please add close keyword ("close") to auto-close the issue.

Where should it be added? 

In the PR title?
In the comment?

**Comment by realshuting** [comment]
> > Please add close keyword ("close") to auto-close the issue.
> 
> Where should it be added?
> 
> In the PR title? In the comment?

In the PR description.

**Comment by realshuting** [comment]
You need to sign your commits https://github.com/kyverno/website/pull/1326/checks?check_run_id=28701366038.

**Review by realshuting — APPROVED** [review]
/lgtm

**Pull request merged**
