### PR TITLE
updated Resource Definitions #173

### PR DESCRIPTION
**Pull request by viveksahu26**
I have made both changes on issue #173.

### CODE REVIEW

**Review by chipzoller — APPROVED** [review]

**Comment by chipzoller** [comment]
@viveksahu26 You must complete the DCO by signing your commits in order for this to be merged.

**Comment by viveksahu26** [comment]
> @viveksahu26 You must complete the DCO by signing your commits in order for this to be merged.

I completed the DCO part. But I want to know more about DCO. What is it exactly? And why we do it.

**Comment by chipzoller** [comment]
CNCF projects require DCO sign off as part of the commit process. If you look at the CI jobs there should be a link.

**Comment by viveksahu26** [comment]
Hey @chipzoller, I am new contribitor. Please don't mine, if I ask silly question. 
I don't understand, what to do next. Is anything left from my side to do. Please let me know.

**Comment by JimBugwadia** [comment]
Hi @viveksahu26 - thanks for your contributions, and no need to apologize for learning! We are happy to help. Nothing more is needed from your side on this PR, I will merge this fix.

However, one note: we also need to fix the actual CRD definition in `https://github.com/kyverno/kyverno/tree/main/pkg/api/kyverno/v1` for the typo. See:

https://github.com/kyverno/kyverno/blob/main/pkg/api/kyverno/v1/policy_types.go#L30

Do you want to submit a PR in `https://github.com/kyverno/kyverno` for that?

**Comment by viveksahu26** [comment]
Yes, I will  do it.

**Pull request merged**
