### PR TITLE
add OWNERS.md

### LINKED ISSUE #1278: [Enhancement] Add a OWNERS.md file
### Description

Required for graduation, add OWNERS.md file

### Slack discussion

_No response_

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: chipzoller <chipzoller@gmail.com>

## Related issue #

Closes #1278

## Proposed Changes

* Adds an OWNERS.md file with all current project maintainers.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
Tagging all maintainers here. If you want your name removed from this file, either comment/suggest or otherwise send your own follow-up PR.

**Review by realshuting — APPROVED** [review]

**Comment by eddycharly** [comment]
Should this complement `CODEOWNERS` ?

**Review by eddycharly — APPROVED** [review]

**Comment by chipzoller** [comment]
Is it required?

**Comment by eddycharly** [comment]
Nope, `CODEOWNERS` had an effect though while `OWNERS.md` is just documentation.

**Comment by chipzoller** [comment]
I think this PR is just to cover the documentation aspect for graduation criteria.

**Comment by eddycharly** [comment]
> I think this PR is just to cover the documentation aspect for graduation criteria.

Got it, thanks!

**Pull request merged**
