### PR TITLE
add loggingFormat flag to installation guide

### PR DESCRIPTION
**Pull request by yimikao**
Signed-off-by: damilola olayinka <holayinkajr@gmail.com>

## Related issue #
[#3411](https://github.com/kyverno/kyverno/issues/3411)
[Pull Request](https://github.com/kyverno/kyverno/pull/4661)

## Proposed Changes

Adds the `--loggingFormat` flag to the list of container flags.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
Hi @yimikao, can you please edit your first post with a link to any PR(s) you have reflecting the code changes? We will need to put this in the same milestone as the code.

**Review by chipzoller — APPROVED** [review]
Needs linked PR and milestone.

**Review by chipzoller — CHANGES_REQUESTED** [review]
My mistake. Please put this new flag in alphabetical order. We are trying to organize the container flags.

**Comment by yimikao** [comment]
@chipzoller done✅

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
