### PR TITLE
docs: installation: scaling: mention kubernetes core components resou…

### PR DESCRIPTION
**Pull request by aborrero**
…rces footprint

Introduce a mention to how many kyverno resources may impact the kubernetes core components regarding their resources footprint.

See also: https://github.com/kyverno/kyverno/issues/10458

## Checklist

- [] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [] I have inspected the website preview for accuracy.
- [] I have signed off my issue.

### CODE REVIEW

**Comment by realshuting** [comment]
Hi @chipzoller - can you help revew?

**Review by chipzoller — COMMENTED** [review]
This seems like it's better for the troubleshooting section than here.

**Comment by aborrero** [comment]
> This seems like it's better for the troubleshooting section than here.

The idea is to prevent folks from having to reach to the troubleshooting section.

I added to the scaling section because I liked the idea of having everything related to the topic of how to operate kyverno at scale on the same page.

Should I have this information here when I started working with kyverno, would have saved me quite a few hours of work.

**Comment by chipzoller** [comment]
But this is a really, really niche concern. Prior to you, we had never heard of people using truly "thousands" of Kyverno policies let alone the problems they might cause.

**Comment by aborrero** [comment]
> But this is a really, really niche concern. Prior to you, we had never heard of people using truly "thousands" of Kyverno policies let alone the problems they might cause.

The troubleshooting section is "after the fact" documentation.

I expect anything related to kubernetes ecosystem to be extremely scalable by default. Ideally, handling a few thousand resources would be no big deal for kyverno.

If handling such a load is not big deal, then it should be clearly documented. But not hidden as an "after the fact" information.

It should be front and center, and in that sense, I can't think of a reason why a section called "scalability" would be the wrong place to put this information.

**Review by JimBugwadia — APPROVED** [review]

**Pull request merged**
