### PR TITLE
Drop down nav bar for mobile

### LINKED ISSUE #238: Enable releases drop-down menu on mobile
From the main kyverno.io page, we need to enable a drop-down in mobile mode that gives users access to the different release branches. Once navigating to a branch, the drop-down doesn't need to exist.

### PR DESCRIPTION
**Pull request by ShubhamPalriwala**
Fixes #238 
- For Desktop, it is as it is before
- For mobile screens, a drop-down menu appears when you click on the button on the right margin that shows the entire nav-bar including a further drop-down for the versions

### For Desktop:
Before | After
-------- | ---------
image | image

### For Mobile:
| Situation |  Screen
-------- | ---------
Idle | 
Clicking on the expand button |  
Drop-down for versions |

### CODE REVIEW

**Comment by ShubhamPalriwala** [comment]
[Preview](https://deploy-preview-258--kyverno.netlify.app/)

**Comment by chipzoller** [comment]
@onweru would you be kind enough to review and provide input?

**Comment by chipzoller** [comment]
@ShubhamPalriwala Looks good to me. Thanks very much for contributing this!

**Comment by onweru** [comment]
> @onweru would you be kind enough to review and provide input?

I checked and it looks good.

**Comment by chipzoller** [comment]
@JimBugwadia please provide review
@ShubhamPalriwala thank you for this!

**Review by JimBugwadia — APPROVED** [review]

**Comment by JimBugwadia** [comment]
Thanks @ShubhamPalriwala!

**Pull request merged**
