### PR TITLE
Creating new section for release note

### PR DESCRIPTION
**Pull request by Anita-ihuman**
PR fixes issue #272

### CODE REVIEW

**Comment by chipzoller** [comment]
I would recommend organizing releases in descending fashion (so the latest release notes are always at the top of the page). This prevents unnecessary scrolling by users.

**Comment by Anita-ihuman** [comment]
> I would recommend organizing releases in descending fashion (so the latest release notes are always at the top of the page). This prevents unnecessary scrolling by users.

are there any more content you think should be included?

**Comment by chipzoller** [comment]
Yes, there's quite a bit more that needs to be listed in each of these releases.

**Comment by Anita-ihuman** [comment]
@chipzoller like the Issue that build up the release right?

**Comment by chipzoller** [comment]
> 
> 
> @chipzoller like the Issue that build up the release right?

I was just thinking a more "human-readable" summarization of the issues/PRs comprising a release. Like adding support for the CONNECT op, a new operator, and breaking out Kyverno into two charts instead of just one.

**Comment by JimBugwadia** [comment]
Are there good example of release notes in the docs for other CNCF / OSS projects that we can reference as an example?

**Comment by Anita-ihuman** [comment]
@chipzoller if you have an example of something I can reference to please share.

**Comment by JimBugwadia** [comment]
@Anita-ihuman - I can't find any examples of an OSS project adding the release notes to the docs, and am wondering if we should just have them in the GitHub repo and reference from the docs?

**Comment by chipzoller** [comment]
Look at the [Antrea project](https://github.com/antrea-io/antrea/releases). Although their release notes aren't in the docs, the way they format and display them is user-friendly enough that they could be picked up and put in the docs as-is.

**Comment by Anita-ihuman** [comment]
@chipzoller That sample looks great. Also, you can look at this example from [openproject](https://www.openproject.org/docs/release-notes/11-0-1/)

**Comment by chipzoller** [comment]
Those notes also look good, although I like have headings for "Fixed" and "New".

**Pull request closed without merging**
