### PR TITLE
Removed not working aws-irsa guide

### PR DESCRIPTION
**Pull request by vponoikoait**
## Related issue #

https://github.com/kyverno/website/issues/1107

## Proposed Changes

Considering that following guide is misleading, as it's not working one 
To be precise - there's a statement in a guide related to usage of AWS signature, but example mentioned in the guide 
```
✗ notation inspect xxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/test-shuting-notation:v1
Inspecting all signatures for signed artifact
xxxxxxxxxxxx.dkr.ecr.us-west-2.amazonaws.com/test-shuting-notation@sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105
└── application/vnd.cncf.notary.signature
    └── sha256:86abf8af48c152f871a5ea56a62a9302e145760089db926420e72c1bbd0de07d
        ├── media type: application/jose+json
        ├── signature algorithm: RSASSA-PSS-SHA-256
        ├── signed attributes
        │   ├── signingScheme: notary.x509
        │   └── signingTime: Fri Aug 11 16:37:40 2023
        ├── user defined attributes
        │   └── (empty)
        ├── unsigned attributes
        │   └── signingAgent: Notation/1.0.0
        ├── certificates
        │   └── SHA256 fingerprint: da1f2d7d648dfacc7ebd59f98a9f35c753c331d80ca4280bb94060f4af4a5357
        │       ├── issued to: CN=test,O=Notary,L=Seattle,ST=WA,C=US
        │       ├── issued by: CN=test,O=Notary,L=Seattle,ST=WA,C=US
        │       └── expiry: Thu May 19 21:15:18 2033
        └── signed artifact
            ├── media type: application/vnd.docker.distribution.manifest.v2+json
            ├── digest: sha256:b31bfb4d0213f254d361e0079deaaebefa4f82ba7aa76ef82e90b4935ad5b105
            └── size: 938
```
Clearly isn't about AWS Signature usage. As we can see here that fingerprints are coming from personal assymetric key - 
```
        │       ├── issued by: CN=test,O=Notary,L=Seattle,ST=WA,C=US
```
And no mention of AWS signature 

## Checklist

- [] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [] I have inspected the website preview for accuracy.
- [] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
cc @realshuting

**Comment by vponoikoait** [comment]
Signer like signature provides similar to next results 
```
└── application/vnd.cncf.notary.signature
    └── sha256:c02c786985c4c56f7a214a4c97cad13c84e094fd0b14cbab1934027619ec4b42
        ├── media type: application/jose+json
        ├── signature algorithm: ECDSA-SHA-384
        ├── signed attributes
        │   ├── expiry: Sat Jan 20 13:50:34 2024
        │   ├── io.cncf.notary.verificationPlugin: com.amazonaws.signer.notation.plugin
        │   ├── com.amazonaws.signer.signingProfileVersion: arn:aws:signer:eu-west-1:000005400154:/signing-profiles/vponoiko_test20240115132817707100000001/e7blvceQzF
        │   ├── com.amazonaws.signer.signingJob: arn:aws:signer:eu-west-1:000005400154:/signing-jobs/cd52c4b2-16f4-40e2-9074-300179e9f43d
        │   ├── signingScheme: notary.x509.signingAuthority
        │   └── signingTime: Wed Jan 17 13:50:34 2024
        ├── user defined attributes
        │   └── (empty)
        ├── unsigned attributes
        │   └── (empty)
        ├── certificates
        │   ├── SHA256 fingerprint: c7f377953e554eaac2782ce22de2b8775636dc2b498b452ac2d30bbfc1ff12a8
        │   │   ├── issued to: CN=AWS Signer,OU=AWS Cryptography,O=AWS,L=Seattle,ST=WA,C=US
        │   │   ├── issued by: CN=AWS Signer eu-west-1 Code Signing CA G1,OU=Cryptography,O=AWS,ST=WA,C=US
        │   │   └── expiry: Sat Jan 20 08:51:59 2024
        │   ├── SHA256 fingerprint: f788eb0b4152a50f99f41ed3234466b9c61c84af12cf3e9dd6b24581ead07ff9
        │   │   ├── issued to: CN=AWS Signer eu-west-1 Code Signing CA G1,OU=Cryptography,O=AWS,ST=WA,C=US
        │   │   ├── issued by: CN=AWS Signer Code Signing Int CA G1,OU=Cryptography,O=AWS,ST=WA,C=US
        │   │   └── expiry: Sun Dec  1 21:36:30 2024
        │   ├── SHA256 fingerprint: eaaac975dcc0d5d160fca1e39834834f014a238cd224d053670982388ccbfca1
        │   │   ├── issued to: CN=AWS Signer Code Signing Int CA G1,OU=Cryptography,O=AWS,ST=WA,C=US
        │   │   ├── issued by: CN=AWS Signer Code Signing Root CA G1,OU=Cryptography,O=AWS,ST=WA,C=US
        │   │   └── expiry: Thu Oct 28 23:18:32 2027
        │   └── SHA256 fingerprint: 90a87d0543c3f094dbff9589b6649affe2f3d6e0f308799be2258461c686473f
        │       ├── issued to: CN=AWS Signer Code Signing Root CA G1,OU=Cryptography,O=AWS,ST=WA,C=US
        │       ├── issued by: CN=AWS Signer Code Signing Root CA G1,OU=Cryptography,O=AWS,ST=WA,C=US
        │       └── expiry: Tue Oct 27 22:33:22 2122
        └── signed artifact
            ├── media type: application/vnd.docker.distribution.manifest.v2+json
            ├── digest: sha256:d1b28da65ab741ea01e9adfd9addc10e26ebb18e0fb3cd1f91d6de49f671cded
            └── size: 2638

```
Current AWS Guide on how to use it is present here:
https://aws.amazon.com/blogs/containers/announcing-container-image-signing-with-aws-signer-and-amazon-eks/
It actually utilises following extension 
https://github.com/nirmata/kyverno-notation-aws 
I can't yet claim it's working properly though

**Comment by chipzoller** [comment]
Converted to draft until other input received.

**Comment by chipzoller** [comment]
@realshuting, were you able to take a look at this?

**Pull request closed without merging**
