### PR TITLE
feat: add kyverno-policies uninstallation method

### PR DESCRIPTION
**Pull request by realshuting**
## Related issue #

https://github.com/kyverno/website/issues/983

## Proposed Changes
This PR adds the installation method to the kyverno-policies chart.

Context: if you have both kyverno and kyverno-policies charts installed and removes the kyverno chart only,  you will get the list error from the API-server when getting the policy:
```
✗ k get cpol
Error from server (NotFound): Unable to list "kyverno.io/v1, Resource=clusterpolicies": the server could not find the requested resource (get clusterpolicies.kyverno.io)
```

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Review by MariamFahmy98 — APPROVED** [review]

**Comment by chipzoller** [comment]
Not sure I quite understand. When you uninstall Kyverno the CRDs go away. If the CRDs go away, all the CRs (the policies) also go away. It's probably nicer and cleaner to also remove the kyverno-policies chart if it has been installed, but why is this a problem?

**Comment by chipzoller** [comment]
Maybe it was just a timing issue? The expected response when a `get` is issued for a resource type that doesn't exist is `error: the server doesn't have a resource type <type>`. I wonder if that would come without uninstalling the `kyverno-policies` chart if you waited longer.

**Comment by chipzoller** [comment]
Need to circle back on this one.

**Comment by realshuting** [comment]
>I wonder if that would come without uninstalling the kyverno-policies chart if you waited longer.

Yes the error indeed was gone if I waited long enough. Closing.

**Pull request closed without merging**
