### PR TITLE
fix styling regressions (snippets, alerts, anchor links)

### PR DESCRIPTION
**Pull request by onweru**
## Proposed Changes

Fixes regressions of Docsy theme update.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by onweru** [comment]
Hi @chipzoller, please check. Will resign with email.

**Comment by chipzoller** [comment]
Hey thanks for this, @onweru. It looks like the code blocks have the outline removed but still not seeing anchor links appear in the preview.

**Comment by onweru** [comment]
@chipzoller, I have restored the anchor links. They were by docsy as part of `v.0.9.0` release via [this PR](https://github.com/google/docsy/pull/1463)

**Comment by chipzoller** [comment]
Ah ok, thanks! I'll have a look at this soon.

**Comment by chipzoller** [comment]
Thanks much!

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
