### PR TITLE
Update customization.md

### PR DESCRIPTION
**Pull request by Rohan-Dah**
This PR is related to issue [#872](https://github.com/kyverno/website/issues/872).

It resolves the occurrence of `kyverno-svc.kyverno.svc` by updating it to `kyverno-svc.<namespace where Kyverno will be installed>.svc`. 

The purpose of this PR is to address the creation of extra Secrets in non-Kyverno namespaces (like Helm), which could conflict with user-created Secrets. Updating the Secret naming convention ensures proper recognition and utilization of existing Secrets, improving installation reliability and consistency.

### CODE REVIEW

**Comment by chipzoller** [comment]
Please direct your changes to the release-1.7 branch.

**Comment by chipzoller** [comment]
You have merged, not cherry picked. You'll probably need to start over here.

**Comment by Rohan-Dah** [comment]
[Here](https://github.com/kyverno/website/pull/916url) is the PR addressing the same issue..

**Comment by chipzoller** [comment]
Remember to sign off on all git commits, per the terms of CNCF project contributions.

**Comment by Rohan-Dah** [comment]
Got it

**Pull request closed without merging**
