### PR TITLE
Updates to dev

### PR DESCRIPTION
**Pull request by chipzoller**

### CODE REVIEW

**Comment by chipzoller** [comment]
@JimBugwadia notice the new "Tips & Tricks" page and see if you like the concept.

**Comment by chipzoller** [comment]
@JimBugwadia could you please review?

**Comment by JimBugwadia** [comment]
@chipzoller - can you please merge `main` to resolve the conflicts?

**Comment by chipzoller** [comment]
@JimBugwadia Resolved conflict using web editor. Merged to main.

**Comment by chipzoller** [comment]
Had to manually restore background and generate pages since they got overwritten in dev with the ones from main.

**Comment by chipzoller** [comment]
Bump @JimBugwadia

**Review by JimBugwadia — APPROVED** [review]

**Pull request merged**
