### PR TITLE
#1444 Removed spell check from Kyverno Architecture image

### PR DESCRIPTION
**Pull request by cerebro1**
## Related issue #

#1444 : https://github.com/kyverno/website/issues/1444

## Proposed Changes

Removed the spell check underline from the text in the Kyverno Architecture image

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

Here is image showing changes on my local.
line_removed_first_issue

### CODE REVIEW

**Review by realshuting — APPROVED** [review]
/lgtm

**Comment by realshuting** [comment]
Thansk @cerebro1 for the fix, can you sign off your commit https://github.com/kyverno/website/pull/1447/checks?check_run_id=34518987705?

**Comment by cerebro1** [comment]
@realshuting Done. Will be careful to add sign-off commit message in the future.

**Comment by cerebro1** [comment]
Hi @realshuting 
Just curious to know who usually approves the workflow. The workflow requires approval from a maintainer for execution even though the PR has been approved by you.

**Comment by cerebro1** [comment]
There is a check showing as failed but this is not related to my changes. Attaching a screenshot for reference.
failed-error

**Review by JimBugwadia — APPROVED** [review]

**Pull request merged**
