### PR TITLE
Update Docsy Theme to 0.8.0

### LINKED ISSUE #1020: [Bug] Search is broken
### Page link

https://main.kyverno.io/docs/

### Description

Search popover does not open anymore. 

I believe the issue was added with https://github.com/kyverno/website/pull/904. 

See console errors:

image

### Expected behavior

Search works.

### Slack discussion

_No response_

### LINKED ISSUE #1080: Mobile menu broken
### Page link

_No response_

### Description

The hamburger menu on mobile is broken.

### Expected behavior

Not broken.

### Slack discussion

_No response_

### PR DESCRIPTION
**Pull request by onweru**
## Proposed Changes
- Upgrade docsy from `v0.7.0` to `v0.8.0`
- Use docsy dedicated [custom scripts file](https://github.com/google/docsy/blob/main/layouts/partials/hooks/body-end.html).  We were overriding the scripts.html file directly, which exposed the website to breaking changes when upgrading.
- Fixes #1020 
- Fixes #1080 
- Consolidate all params to `params.toml` file
- Renames a js script that result in name conflicts after the 0.8.0 theme upgrade.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by onweru** [comment]
@chipzoller, 

I have resolved #1020, but need to cleanup one file. Everything else works well. Please test in the meantime.

**Comment by chipzoller** [comment]
Code blocks appear to be off now. See [here](https://deploy-preview-1030--kyverno.netlify.app/policies/pod-security-cel/baseline/disallow-capabilities/disallow-capabilities/).

**Comment by chipzoller** [comment]
@onweru, thanks again. Do you mind resolving the conflict created after we cut the 1.11 docs?

**Comment by onweru** [comment]
> @onweru, thanks again. Do you mind resolving the conflict created after we cut the 1.11 docs?

@chipzoller, it's done.

**Comment by chipzoller** [comment]
There appears to be some duplication of anchor links in the preview, @onweru.

image

**Comment by chipzoller** [comment]
After going through the PR, I think those are the only two things!

**Comment by chipzoller** [comment]
Just realized that the hamburger menu on mobile doesn't work 🤦‍♂️

**Comment by chipzoller** [comment]
Gentle bump on this, @onweru!

**Comment by chipzoller** [comment]
Search doesn't work.

**Comment by chipzoller** [comment]
Build is failing here.

**Review by chipzoller — APPROVED** [review]

**Comment by chipzoller** [comment]
Much appreciated, as always, @onweru!

**Pull request merged**
