### PR TITLE
fix: certificates docs

### LINKED ISSUE #836: [Enhancement] Revise self-sign certs flow
### Description

The process currently documented [here](https://kyverno.io/docs/installation/#option-2-use-your-own-ca-signed-certificate) for self-signed certificates needs to be revised for Kyverno 1.10.

@eddycharly, please help with this.

### Slack discussion

_No response_

### PR DESCRIPTION
**Pull request by eddycharly**
## Related issue #

This PR revisits certificates docs.

Fixes #836

### CODE REVIEW

**Review by chipzoller — COMMENTED** [review]
Have you tested this procedure as it's written here? And does it work?

**Comment by eddycharly** [comment]
> Have you tested this procedure as it's written here? And does it work?

Nope, i don't even know this step tool.

I removed the reference to the unmaintained script and added instructions to generate cleanup controller certs based on what we had for the admission controller.

**Comment by chipzoller** [comment]
The procedure needs to be tested firsthand.

**Comment by eddycharly** [comment]
@chipzoller i tried it, it didn't work, then i fixed the docs and tried it again.

It's working now.

**Comment by eddycharly** [comment]
We needed `--kty=RSA` when creating the certs.

**Review by chipzoller — APPROVED** [review]
Thank you. This is exactly why we must personally test and validate every line in the docs. It's also why it makes docs refreshes lengthy and sometimes not that fun. But they must be done.

**Pull request merged**
