### PR TITLE
feat: add CLI reference docs

### PR DESCRIPTION
**Pull request by eddycharly**
## Related issue #

This PR adds CLI reference docs.

### CODE REVIEW

**Review by chipzoller — COMMENTED** [review]
This should really go as a sub-section under the "Kyverno CLI" heading we already have rather than a new top-level section.

**Comment by eddycharly** [comment]
Ok, i'll look how to do that.

**Comment by chipzoller** [comment]
All you've gotta do is make folders. See what we did with the verify-images one here: https://github.com/kyverno/website/tree/main/content/en/docs/Writing%20policies/verify-images

**Comment by chipzoller** [comment]
Still looking for changes here. Additionally, how will we maintain these? How will we be able to update them? Do you have a procedure?

**Review by chipzoller — CHANGES_REQUESTED** [review]
This should really go as a sub-section under the "Kyverno CLI" heading we already have rather than a new top-level section.

**Comment by chipzoller** [comment]
Bump

**Comment by chipzoller** [comment]
No response, closed.

**Comment by eddycharly** [comment]
Reopening, need to get this in :)

**Comment by eddycharly** [comment]
Closing, will come with https://github.com/kyverno/website/pull/1179

**Pull request closed without merging**
