### PR TITLE
Check links on PR; fix links

### PR DESCRIPTION
**Pull request by chipzoller**
Signed-off-by: chipzoller <chipzoller@gmail.com>

## Proposed Changes

Implements the link checker on PR with failing behavior and fixes found links. Enables Dependabot for Actions.

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
I'm not sure if there's a way to configure the `--base` parameter correctly based on all the link styles we have.

**Comment by chipzoller** [comment]
In this latest failure, the links will work once the production branch gets switched over.

We seem to face a problem here when it comes to reliably testing for broken links of intra-site links. We specify relative links in these Markdown files in a couple of ways:

* relative HTML path (based on the base URL), ex. `/docs/writing-policies/exceptions`. This is only relative when rendered. The file system path is `/docs/Writing Policies/exceptions.md`
* images with an implicit search beginning at `/static`
* "wrong"(?) relative path from now-automated CLI reference docs, ex., `../kyverno` where the file is not one level up but on the same. Somehow this gets rendered properly.

For now, the link checker is rendering the site using Hugo and then checking the rendered files and not the raw source files. This seems to be the most reliable out of all tested configurations, but the problem it causes any new intra-site links that are not also present on the "live" version of https://kyverno.io it will say fail since the changes in the PR obviously do not exist on the prod site yet. Really not sure how to handle this as of yet. I think we can at least get this PR in but leave this link checker in a "soft" state (not required to merge a PR) until we find a better solution. I'm just hoping the solution doesn't involve walking across the site and changing ALL links to a supported format along with changing the directory structure.

**Comment by chipzoller** [comment]
The tip was the kicker!

We still have a challenge in that we can't catch links with anchors which have changed where the parent page still exists.

**Review by realshuting — APPROVED** [review]
Awesome👍

**Pull request merged**
