### PR TITLE
cherry pick version 1.5.0

### PR DESCRIPTION
**Pull request by Anita-ihuman**
Signed-off-by: Anita-ihuman <charlesanita403@gmail.com>

### CODE REVIEW

**Comment by JimBugwadia** [comment]
@Anita-ihuman - since the PR to `main` had separate commits, you will need to include all of those changes into the `release-1-5-0` branch. See:

https://github.com/kyverno/website/pull/386/commits

Can you please cherry-pick / merge the remaining changes?

You can check the new site using the Deployment Preview shown above:

https://deploy-preview-390--kyverno.netlify.app/

**Review by JimBugwadia — CHANGES_REQUESTED** [review]
See comment:

> @Anita-ihuman - since the PR to main had separate commits, you will need to include all of those changes into the release-1-5-0 branch. See:

> https://github.com/kyverno/website/pull/386/commits
>
> Can you please cherry-pick / merge the remaining changes?
>
> You can check the new site using the Deployment Preview shown above:
>
> https://deploy-preview-390--kyverno.netlify.app/

**Comment by Anita-ihuman** [comment]
@JimBugwadia Looks like it's working just fine now.

**Review by JimBugwadia — APPROVED** [review]

**Comment by JimBugwadia** [comment]
Nice, @Anita-ihuman! Merged!

**Pull request merged**
