### PR TITLE
update sample policies

### PR DESCRIPTION
**Pull request by JimBugwadia**
- added usage for sample policies
- removed categories from markdown
- added logic to use `title` annotation if present
- added instructions on rendering markdown

### CODE REVIEW

**Comment by JimBugwadia** [comment]
I also changed the search to use a local search.

You can try it at: https://deploy-preview-56--kyverno.netlify.app/

**Comment by chipzoller** [comment]
> I also changed the search to use a local search.
> 
> You can try it at: https://deploy-preview-56--kyverno.netlify.app/

Some comments noted [here](https://github.com/kyverno/website/issues/33#issuecomment-752647696).

**Review by chipzoller — APPROVED** [review]
This all looks nice. The title annotation is a nice touch as well. I'll try and go back and ensure all the policies have a description.

**Comment by JimBugwadia** [comment]
@chipzoller - here is a corresponding PR for the policies (titles, descriptions, etc.): https://github.com/kyverno/policies/pull/7.

**Pull request merged**
