### PR TITLE
Add 1.12 load testing data

### PR DESCRIPTION
**Pull request by realshuting**
## Related issue #
Relate to https://github.com/kyverno/website/issues/1145.

## Proposed Changes
This PR adds k6 load testing data for 1.12.0. It mainly focuses on the admission controller. 

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Review by KhaledEmaraDev — APPROVED** [review]

**Comment by realshuting** [comment]
Reports controller will be covered in https://github.com/kyverno/website/pull/1218.

**Comment by chipzoller** [comment]
> Reports controller will be covered in #1218.

Huh? That's a blog post about the (separate) external reports project. Doesn't have anything to do with performance figures around the built-in reports controller.

**Comment by realshuting** [comment]
> > Reports controller will be covered in #1218.
> 
> Huh? That's a blog post about the (separate) external reports project. Doesn't have anything to do with performance figures around the built-in reports controller.

The test setup for the admission controller is different from the report controller. We can do the dry-run during the admission review process to measure the latency, but we need more Kubernetes nodes to generate more reports (workloads).  We are setting up the test environment for the reports controller and will be load-testing the reports controller with and without the new report server. The numbers will be added in the same PR.

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
