### PR TITLE
bugfix: `Render` to cleanup all the directories

### LINKED ISSUE #929: [Enhancement] `render` utility does not clean directories
### Description

When using the `-c` flag to `render`, it does not remove directories. Unsure if bug or oversight.

### Slack discussion

_No response_

### PR DESCRIPTION
**Pull request by A-5ingh**
## Related issue #
Fixes #929 

## Proposed Changes

The bug was due to the code not recursively searching the directory for `.md` files. We have modified the code to search directories and sub-directories. 

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
How does this actually remove the directories themselves? That is the actual issue, not failing to remove the Markdown files.

**Comment by A-5ingh** [comment]
This change will remove the md files from the output folder. Let me check one more time. 
But I see the directories should be deleted too.

**Comment by A-5ingh** [comment]
> How does this actually remove the directories themselves? That is the actual issue, not failing to remove the Markdown files.

I thought and also tested locally that the issue is the when using `-c` option, it is not removing the `*.md` files. 
Do we want to delete the root directory itself? I think that will be more simpler/cleaner.

**Comment by A-5ingh** [comment]
> We want to clear whatever directory is given as the render target. If the render target is `/policies` then I would expect render to remove all files and directories inside `/policies` when the `-c` flag is provided.

Thank you for the clarification. I will modify the code and push new commits.

**Comment by A-5ingh** [comment]
https://github.com/kyverno/website/blob/f82fc7b4199349bef3dd633be264ea0c947b208a/render/render.go#L208-L210

@chipzoller  Can you please confirm if we still have to exclude `_index.md` files from deletion even with `-c` option? Because we are going to delete the target folder then all the files will be deleted.

**Comment by chipzoller** [comment]
>Because we are going to delete the target folder then all the files will be deleted.

No, we don't want to delete the target folder, we simply want to delete everything inside of it (files and folders) EXCEPT `_index.md`.

**Comment by A-5ingh** [comment]
@chipzoller Kindly review and test it once now. 
When a user passes `-c` argument to the render function, then it will perform below steps.
 - Delete all the `*.md` files from the output folder passed with exception to `_index.md`.
 - Delete all the empty sub directories in the output folder.

**Review by JimBugwadia — APPROVED** [review]

**Pull request merged**
