### PR TITLE
Fix broken link and update ArgoCD header URL"

### PR DESCRIPTION
**Pull request by lakshmanandevops**
## Related issue

#1448 

## Proposed Changes

This PR addresses two issues in the documentation

- Fixes a broken link to the GitHub repository by updating it with the correct URL.
- Corrects the ArgoCD header name in the URL to ensure it accurately points to the right section.

Files Modified:

content/en/blog/general/introducing-kyverno-envoy-plugin/index.md
image

content/en/docs/writing-policies/mutate.md
image

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by realshuting** [comment]
Thanks for the contribution @lakshmanandevops ! Can you please [sign off your commits](https://github.com/kyverno/website/pull/1451/checks?check_run_id=34696534495)?

**Comment by lakshmanandevops** [comment]
@realshuting I see that DCO check is keep failing due to the Author email mismatch between local and github account. I have tried the steps to fix but it does not seem to work. Please let me know if it is okay to close this PR and raise a new PR with properly signed commit. Apologies for the inconvenience

**Comment by realshuting** [comment]
> Please let me know if it is okay to close this PR and raise a new PR with properly signed commit. 

Yes sounds good!

**Comment by lakshmanandevops** [comment]
Closing the PR due to an issue with Signed Off Commits. Will raise a new PR

**Pull request closed without merging**
