### PR TITLE
changed the readme.md and contributing.md file

### PR DESCRIPTION
**Pull request by brf153**
## Related to issue #921 ##

@chipzoller I have removed the --recurse-submodule option from the contributing.md and readme.md file.

### CODE REVIEW

**Review by chipzoller — CHANGES_REQUESTED** [review]
Would be great if you can also:
* Remove the `-v` flag
* Add a note for Windows users that this should be run from an elevated command prompt

**Comment by brf153** [comment]
@chipzoller I have done the changes that you have suggested. Please check my PR.

**Comment by chipzoller** [comment]
Still need you to sign off here.

**Comment by brf153** [comment]
Can I leave a comment here for signing off ? Like Signed-off-by: @brf153  <https://github.com/brf153>

**Comment by brf153** [comment]
@chipzoller Please check

**Comment by chipzoller** [comment]
Still not signed off.

**Review by chipzoller — CHANGES_REQUESTED** [review]
DCO is required for all CNCF projects.

**Comment by brf153** [comment]
@chipzoller Please check now

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
