### PR TITLE
[Blog] Assigning Node Metadata to pods

### PR DESCRIPTION
**Pull request by chipzoller**
https://deploy-preview-1161--kyverno.netlify.app/blog/2024/02/19/assigning-node-metadata-to-pods/

## Proposed Changes

Adds a new blog entitled "Assigning Node Metadata to pods"

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
Sorry for the noise, folks. We need to figure out how to allow requesting review from the maintainers group without having to approve every message.

**Review by MariamFahmy98 — APPROVED** [review]
This blog provides valuable insights!

**Comment by chipzoller** [comment]
No other reviews provided. Merging.

**Pull request merged**
