### PR TITLE
feat (generate): add orphanDownstreamOnPolicyDelete to preserve downstream on policy deletion 

### PR DESCRIPTION
**Pull request by realshuting**
## Related issue #
https://github.com/kyverno/kyverno/pull/9579

## Checklist

- [x] I have read the [contributing guidelines](https://github.com/kyverno/website/blob/main/CONTRIBUTING.md).
- [x] I have inspected the website preview for accuracy.
- [x] I have signed off my issue.

### CODE REVIEW

**Comment by chipzoller** [comment]
This flag also needs some behavior explanation elsewhere in this same section about "what if" scenarios.

**Comment by realshuting** [comment]
> This flag also needs some behavior explanation elsewhere in this same section about "what if" scenarios.

Not sure I get it, can you elaborate?

**Comment by chipzoller** [comment]
The questions I asked in the PR, specifically what happens when the rule is reintroduced.

**Comment by realshuting** [comment]
> The questions I asked in the PR, specifically what happens when the rule is reintroduced.

I missed that. Replied in the same PR and pasting responses here, will update accordingly.

>1. This new field will be defaulted to false if not present?

Yes.

>2. What happens if someone sets it to true for a clone-type rule?

No-effect for a clone-type rule as policy events don't apply to generated resources.

>3a. What happens if they set it to true, delete the rule/policy, and recreate it exactly? 

Everything works the same, the policy will be applied 1.) based on generateExisting setting; 2.) on new trigger's events.

>3. Are the downstream resources left behind going to resume syncing if synchronize is enabled?

Yes.

>4a. What about above but if they start modifying things in that rule which was deleted and recreated? 

Same with 3a.

>4b. Will the new rule start owning the same previously-generated resources?

Yes.

**Review by chipzoller — APPROVED** [review]

**Pull request merged**
